var BAIDU_LBS_AK = 'X3DHGwacZnlP5QfTsyGO72nC',
	HTTP_WWW = 'http://www.nongji360.mobi',
	HTTP_AUTH = 'http://auth.nongji360.mobi',
	HTTP_NEWS = 'http://news.nongji360.mobi',
	HTTP_VIDEO = 'http://v.nongji360.mobi',
	HTTP_IMAGE = 'http://image.nongji360.mobi',
	HTTP_CODE = 'http://code.nongji360.mobi',
	HTTP_IMG = 'http://img2.nongji360.mobi',
	HTTP_VIDEO_FILE = 'http://datasp1.nongji360.mobi',
	HTTP_USER = 'http://my.nongji360.mobi',
	HTTP_MOBILE_USER = 'http://m.my.nongji360.mobi',
	HTTP_COMMENT = 'http://comment.nongji360.mobi',
	HTTP_ZT = 'http://zt.nongji360.mobi',
	HTTP_WD = 'http://wd.nongji360.mobi',
	HTTP_API = 'http://api.nongji360.mobi',
	HTTP_O2O = 'http://o2o.nongji360.mobi',
	HTTP_SHEQU = 'http://shequ.nongji360.mobi',
	HTTP_SHEQU_MOBILE = 'http://m.shequ.nongji360.mobi',
	HTTP_MOBILE = 'http://m.nongji360.mobi',
	HTTP_SO = 'http://so.nongji360.mobi',
	HTTP_ITEM = 'http://item.nongji360.mobi',
	NONGJI_DOMAIN = 'nongji360.mobi',
	HTTP_QINIU_SHEQU_VIDEO = 'https://qiniu-video.nongji360.com',
	HTTP_QINIU_SHEQU_VIDEO_V = 'https://qiniu-video-v.nongji360.com';

var SHARE_DOMAIN = [
		HTTP_AUTH+'/cross/p3p',
	'http://www.dtzl360.net/cross/p3p',
	'http://m-jie.datian360.net/cross/p3p'
];